/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, visit the plugin repo.
*/
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TextProcessorPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  actions: [
    {
      id: "builtin-heading-to-text",
      name: "\u6807\u9898\u964D\u7EA7\u4E3A\u666E\u901A\u6587\u672C",
      // 去掉行首的若干个 # 号及其后的一个空格
      code: "// \u53BB\u6389\u884C\u9996\u7684 # \u53F7\u53CA\u5176\u540E\u7684\u4E00\u4E2A\u7A7A\u683C\uFF08\u591A\u4E2A # \u4E5F\u4F1A\u4E00\u8D77\u53BB\u6389\uFF09\nreturn text.replace(/^#+\\s+/gm, '');"
    },
    {
      id: "builtin-remove-extra-blank-lines",
      name: "\u53BB\u9664\u591A\u4F59\u7A7A\u884C",
      // 连续多个“空行或只有空格/全角空格的行”合并为一个空行
      code: "const lines = text.split('\\n');\nconst out = [];\nlet prevBlank = false;\nfor (const line of lines) {\n  const isBlank = /^[\\s\\u3000]*$/.test(line);\n  if (isBlank) {\n    if (!prevBlank) out.push('');\n    prevBlank = true;\n  } else {\n    out.push(line);\n    prevBlank = false;\n  }\n}\nreturn out.join('\\n');"
    }
  ],
  sequences: [
    {
      id: "builtin-demo-sequence",
      name: "\u793A\u8303\u5E8F\u5217\uFF1A\u6807\u9898\u964D\u7EA7 + \u53BB\u7A7A\u884C",
      steps: [
        { actionId: "builtin-heading-to-text" },
        { actionId: "builtin-remove-extra-blank-lines" }
      ]
    }
  ]
};

// src/actions.ts
function compileAction(code) {
  const fn = new Function("text", code);
  return (text) => {
    const result = fn(text);
    if (typeof result !== "string") {
      throw new Error("\u52A8\u4F5C\u4EE3\u7801\u6CA1\u6709 return \u4E00\u4E2A\u5B57\u7B26\u4E32\uFF08\u8BF7\u786E\u8BA4\u6700\u540E\u6709 return\uFF09");
    }
    return result;
  };
}
function runAction(action, text) {
  return compileAction(action.code)(text);
}
function runSequence(sequence, actionsById, text) {
  let current = text;
  for (const step of sequence.steps) {
    const action = actionsById.get(step.actionId);
    if (!action) continue;
    current = runAction(action, current);
  }
  return current;
}

// src/settings.ts
var import_obsidian = require("obsidian");
var TextProcessorSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u52A8\u4F5C\uFF08\u53EF\u81EA\u5B9A\u4E49\u4EE3\u7801\uFF09" });
    new import_obsidian.Setting(containerEl).setName("\u65B0\u589E\u52A8\u4F5C").setDesc("\u52A8\u4F5C\u662F\u4E00\u6BB5 JavaScript \u4EE3\u7801\uFF1A\u62FF\u5230\u53D8\u91CF text\uFF0Creturn \u5904\u7406\u540E\u7684\u5B57\u7B26\u4E32\u3002").addButton(
      (btn) => btn.setButtonText("+ \u65B0\u589E\u52A8\u4F5C").onClick(() => {
        this.plugin.settings.actions.push({
          id: "action-" + Date.now().toString(36),
          name: "\u65B0\u52A8\u4F5C",
          code: "return text;"
        });
        this.plugin.saveSettings();
        this.display();
      })
    );
    this.plugin.settings.actions.forEach((action, index) => {
      const setting = new import_obsidian.Setting(containerEl).setName(`\u52A8\u4F5C ${index + 1}`);
      const nameInput = new import_obsidian.TextComponent(setting.controlEl);
      nameInput.setValue(action.name).setPlaceholder("\u52A8\u4F5C\u540D\u79F0");
      nameInput.inputEl.style.marginRight = "8px";
      nameInput.onChange((v) => {
        action.name = v;
        this.plugin.saveSettings();
      });
      setting.addButton(
        (btn) => btn.setButtonText(action.favorite ? "\u2605 \u5E38\u7528" : "\u2606 \u5E38\u7528").setCta(action.favorite).onClick(() => {
          action.favorite = !action.favorite;
          this.plugin.saveSettings();
          this.display();
        })
      );
      setting.addButton(
        (btn) => btn.setButtonText("\u5220\u9664").onClick(() => {
          this.plugin.settings.actions.splice(index, 1);
          this.plugin.settings.sequences.forEach((seq) => {
            seq.steps = seq.steps.filter((s) => s.actionId !== action.id);
          });
          this.plugin.saveSettings();
          this.display();
        })
      );
      const codeSetting = new import_obsidian.Setting(containerEl).setName("\u4EE3\u7801");
      codeSetting.addTextArea((ta) => {
        ta.setValue(action.code).onChange((v) => {
          action.code = v;
          this.plugin.saveSettings();
        });
        ta.inputEl.rows = 4;
        ta.inputEl.classList.add("text-batch-code");
        ta.inputEl.style.width = "100%";
      });
    });
    containerEl.createEl("h2", { text: "\u5E8F\u5217\uFF08\u52A8\u4F5C\u7684\u7EC4\u5408\uFF09" });
    new import_obsidian.Setting(containerEl).setName("\u65B0\u589E\u5E8F\u5217").setDesc("\u628A\u591A\u4E2A\u52A8\u4F5C\u6309\u987A\u5E8F\u6392\u5217\uFF0C\u5F62\u6210\u53EF\u4E00\u952E\u6267\u884C\u7684\u5E8F\u5217\u3002").addButton(
      (btn) => btn.setButtonText("+ \u65B0\u589E\u5E8F\u5217").onClick(() => {
        this.plugin.settings.sequences.push({
          id: "seq-" + Date.now().toString(36),
          name: "\u65B0\u5E8F\u5217",
          steps: []
        });
        this.plugin.saveSettings();
        this.display();
      })
    );
    this.plugin.settings.sequences.forEach((seq, seqIndex) => {
      const setting = new import_obsidian.Setting(containerEl).setName(`\u5E8F\u5217 ${seqIndex + 1}`);
      const nameInput = new import_obsidian.TextComponent(setting.controlEl);
      nameInput.setValue(seq.name).setPlaceholder("\u5E8F\u5217\u540D\u79F0");
      nameInput.inputEl.style.marginRight = "8px";
      nameInput.onChange((v) => {
        seq.name = v;
        this.plugin.saveSettings();
      });
      setting.addButton(
        (btn) => btn.setButtonText(seq.favorite ? "\u2605 \u5E38\u7528" : "\u2606 \u5E38\u7528").setCta(seq.favorite).onClick(() => {
          seq.favorite = !seq.favorite;
          this.plugin.saveSettings();
          this.display();
        })
      );
      setting.addButton(
        (btn) => btn.setButtonText("\u5220\u9664\u5E8F\u5217").onClick(() => {
          this.plugin.settings.sequences.splice(seqIndex, 1);
          this.plugin.saveSettings();
          this.display();
        })
      );
      seq.steps.forEach((step, stepIndex) => {
        const action = this.plugin.settings.actions.find(
          (a) => a.id === step.actionId
        );
        const stepSetting = new import_obsidian.Setting(containerEl).setName(
          `\u6B65\u9AA4 ${stepIndex + 1}` + (action ? `\uFF1A${action.name}` : "\uFF1A\uFF08\u52A8\u4F5C\u5DF2\u5220\u9664\uFF09")
        );
        stepSetting.addButton(
          (btn) => btn.setButtonText("\u2191 \u4E0A\u79FB").onClick(() => {
            if (stepIndex > 0) {
              const tmp = seq.steps[stepIndex - 1];
              seq.steps[stepIndex - 1] = seq.steps[stepIndex];
              seq.steps[stepIndex] = tmp;
              this.plugin.saveSettings();
              this.display();
            }
          })
        );
        stepSetting.addButton(
          (btn) => btn.setButtonText("\u2193 \u4E0B\u79FB").onClick(() => {
            if (stepIndex < seq.steps.length - 1) {
              const tmp = seq.steps[stepIndex + 1];
              seq.steps[stepIndex + 1] = seq.steps[stepIndex];
              seq.steps[stepIndex] = tmp;
              this.plugin.saveSettings();
              this.display();
            }
          })
        );
        stepSetting.addButton(
          (btn) => btn.setButtonText("\u5220\u9664\u6B65\u9AA4").onClick(() => {
            seq.steps.splice(stepIndex, 1);
            this.plugin.saveSettings();
            this.display();
          })
        );
      });
      const addSetting = new import_obsidian.Setting(containerEl).setName("\u6DFB\u52A0\u52A8\u4F5C\u5230\u5E8F\u5217");
      const dropdown = new import_obsidian.DropdownComponent(addSetting.controlEl);
      this.plugin.settings.actions.forEach((a) => dropdown.addOption(a.id, a.name));
      addSetting.addButton(
        (btn) => btn.setButtonText("\u6DFB\u52A0").onClick(() => {
          const val = dropdown.getValue();
          if (val) {
            seq.steps.push({ actionId: val });
            this.plugin.saveSettings();
            this.display();
          }
        })
      );
    });
  }
};

// src/picker.ts
var import_obsidian2 = require("obsidian");
var PickerModal = class extends import_obsidian2.FuzzySuggestModal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
    this.setPlaceholder("\u9009\u62E9\u8981\u6267\u884C\u7684\u52A8\u4F5C\u6216\u5E8F\u5217\u2026");
  }
  getItems() {
    const settings = this.plugin.settings;
    const favActions = settings.actions.filter((a) => a.favorite).map((a) => ({ kind: "action", action: a }));
    const favSeqs = settings.sequences.filter((s) => s.favorite).map((s) => ({ kind: "sequence", sequence: s }));
    const restActions = settings.actions.filter((a) => !a.favorite).map((a) => ({ kind: "action", action: a }));
    const restSeqs = settings.sequences.filter((s) => !s.favorite).map((s) => ({ kind: "sequence", sequence: s }));
    return [...favActions, ...favSeqs, ...restActions, ...restSeqs];
  }
  getItemText(item) {
    const star = item.kind === "action" ? item.action.favorite ? "\u2605 " : "" : item.sequence.favorite ? "\u2605 " : "";
    return star + (item.kind === "action" ? "\u52A8\u4F5C\uFF1A" + item.action.name : "\u5E8F\u5217\uFF1A" + item.sequence.name);
  }
  onChooseItem(item) {
    const editor = this.plugin.app.workspace.getActiveViewOfType(import_obsidian2.MarkdownView)?.editor;
    if (!editor) {
      new import_obsidian2.Notice("\u8BF7\u5148\u6253\u5F00\u4E00\u7BC7\u7B14\u8BB0");
      return;
    }
    const selection = editor.getSelection();
    try {
      if (item.kind === "action") {
        const out = selection ? runAction(item.action, selection) : runAction(item.action, editor.getValue());
        if (selection) editor.replaceSelection(out);
        else editor.setValue(out);
      } else {
        const map = this.plugin.getActionsMap();
        const out = selection ? runSequence(item.sequence, map, selection) : runSequence(item.sequence, map, editor.getValue());
        if (selection) editor.replaceSelection(out);
        else editor.setValue(out);
      }
    } catch (e) {
      new import_obsidian2.Notice("\u6267\u884C\u51FA\u9519\uFF1A" + e.message);
    }
  }
};

// src/main.ts
var TextProcessorPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.commandIds = [];
    // 桌面端右键菜单：仅当选中文本时显示。
    // 说明：Obsidian 右键菜单的“子菜单”依赖未公开 API setSubmenu，在你这版 Obsidian 上渲染不稳定
    // （点了没反应、不显示展开箭头）。因此这里改为：点击“文本批处理”直接弹出选择对话框
    // （模糊搜索，常用项置顶），交互最稳、也最接近最初“弹出对话框选择动作/序列”的设计。
    this.onEditorMenu = (menu, editor) => {
      const selection = editor.getSelection();
      if (!selection) return;
      menu.addItem(
        (item) => item.setTitle("\u6587\u672C\u6279\u5904\u7406").setIcon("text-cursor-input").onClick(() => {
          new PickerModal(this.app, this).open();
        })
      );
    };
  }
  async onload() {
    await this.loadSettings();
    this.registerAllCommands();
    this.addSettingTab(new TextProcessorSettingTab(this.app, this));
    this.registerEvent(this.app.workspace.on("editor-menu", this.onEditorMenu));
  }
  onunload() {
  }
  async loadSettings() {
    const data = await this.loadData();
    this.settings = data ? { ...DEFAULT_SETTINGS, ...data } : JSON.parse(JSON.stringify(DEFAULT_SETTINGS));
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.registerAllCommands();
  }
  getActionsMap() {
    return new Map(this.settings.actions.map((a) => [a.id, a]));
  }
  fullId(id) {
    return `${this.manifest.id}:${id}`;
  }
  clearCommands() {
    for (const id of this.commandIds) {
      this.app.commands.removeCommand(id);
    }
    this.commandIds = [];
  }
  registerAllCommands() {
    this.clearCommands();
    this.addCommand({
      id: "open-picker",
      name: "\u9009\u62E9\u52A8\u4F5C\u6216\u5E8F\u5217\uFF08\u83DC\u5355\uFF09",
      callback: () => {
        new PickerModal(this.app, this).open();
      }
    });
    this.commandIds.push(this.fullId("open-picker"));
    for (const action of this.settings.actions) {
      this.addCommand({
        id: `action:${action.id}`,
        name: `\u52A8\u4F5C\uFF1A${action.name}`,
        editorCallback: (editor) => this.runOnEditor(editor, (t) => runAction(action, t))
      });
      this.commandIds.push(this.fullId(`action:${action.id}`));
    }
    const map = this.getActionsMap();
    for (const seq of this.settings.sequences) {
      this.addCommand({
        id: `sequence:${seq.id}`,
        name: `\u5E8F\u5217\uFF1A${seq.name}`,
        editorCallback: (editor) => this.runOnEditor(editor, (t) => runSequence(seq, map, t))
      });
      this.commandIds.push(this.fullId(`sequence:${seq.id}`));
    }
  }
  // 在编辑器上执行：有选区就处理选区，没选区就处理整篇
  runOnEditor(editor, transform) {
    const selection = editor.getSelection();
    try {
      if (selection) {
        editor.replaceSelection(transform(selection));
      } else {
        editor.setValue(transform(editor.getValue()));
      }
    } catch (e) {
      new import_obsidian3.Notice("\u6587\u672C\u6279\u5904\u7406\u6267\u884C\u51FA\u9519\uFF1A" + e.message);
    }
  }
};
